/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as RentRouteImport } from './routes/rent'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RentSlugRouteImport } from './routes/rent.$slug'
import { Route as PurposeSlugRouteImport } from './routes/purpose.$slug'
import { Route as GamesGuessTheCarRouteImport } from './routes/games.guess-the-car'
import { Route as GamesEngineSoundRouteImport } from './routes/games.engine-sound'
import { Route as CarsSlugRouteImport } from './routes/cars.$slug'
import { Route as BrandsBrandRouteImport } from './routes/brands.$brand'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuctionsSlugRouteImport } from './routes/auctions.$slug'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminRentalsRouteImport } from './routes/admin.rentals'
import { Route as AdminPurposePagesRouteImport } from './routes/admin.purpose-pages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAuctionsRouteImport } from './routes/admin.auctions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentSlugRoute = RentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RentRoute,
} as any)
const PurposeSlugRoute = PurposeSlugRouteImport.update({
  id: '/purpose/$slug',
  path: '/purpose/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGuessTheCarRoute = GamesGuessTheCarRouteImport.update({
  id: '/guess-the-car',
  path: '/guess-the-car',
  getParentRoute: () => GamesRoute,
} as any)
const GamesEngineSoundRoute = GamesEngineSoundRouteImport.update({
  id: '/engine-sound',
  path: '/engine-sound',
  getParentRoute: () => GamesRoute,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandRoute = BrandsBrandRouteImport.update({
  id: '/brands/$brand',
  path: '/brands/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuctionsSlugRoute = AuctionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuctionsRoute,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/admin/rentals',
  path: '/admin/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPurposePagesRoute = AdminPurposePagesRouteImport.update({
  id: '/admin/purpose-pages',
  path: '/admin/purpose-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/admin/games',
  path: '/admin/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/admin/brands',
  path: '/admin/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/admin/auctions',
  path: '/admin/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/buy': typeof BuyRoute
  '/fleet': typeof FleetRoute
  '/games': typeof GamesRouteWithChildren
  '/history': typeof HistoryRoute
  '/rent': typeof RentRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/purpose-pages': typeof AdminPurposePagesRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/games/engine-sound': typeof GamesEngineSoundRoute
  '/games/guess-the-car': typeof GamesGuessTheCarRoute
  '/purpose/$slug': typeof PurposeSlugRoute
  '/rent/$slug': typeof RentSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/buy': typeof BuyRoute
  '/fleet': typeof FleetRoute
  '/games': typeof GamesRouteWithChildren
  '/history': typeof HistoryRoute
  '/rent': typeof RentRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/purpose-pages': typeof AdminPurposePagesRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/games/engine-sound': typeof GamesEngineSoundRoute
  '/games/guess-the-car': typeof GamesGuessTheCarRoute
  '/purpose/$slug': typeof PurposeSlugRoute
  '/rent/$slug': typeof RentSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/buy': typeof BuyRoute
  '/fleet': typeof FleetRoute
  '/games': typeof GamesRouteWithChildren
  '/history': typeof HistoryRoute
  '/rent': typeof RentRouteWithChildren
  '/vault': typeof VaultRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/purpose-pages': typeof AdminPurposePagesRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auctions/$slug': typeof AuctionsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/games/engine-sound': typeof GamesEngineSoundRoute
  '/games/guess-the-car': typeof GamesGuessTheCarRoute
  '/purpose/$slug': typeof PurposeSlugRoute
  '/rent/$slug': typeof RentSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auctions'
    | '/blog'
    | '/buy'
    | '/fleet'
    | '/games'
    | '/history'
    | '/rent'
    | '/vault'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/games'
    | '/admin/history'
    | '/admin/homepage'
    | '/admin/logs'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/purpose-pages'
    | '/admin/rentals'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auctions/$slug'
    | '/blog/$slug'
    | '/brands/$brand'
    | '/cars/$slug'
    | '/games/engine-sound'
    | '/games/guess-the-car'
    | '/purpose/$slug'
    | '/rent/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auctions'
    | '/blog'
    | '/buy'
    | '/fleet'
    | '/games'
    | '/history'
    | '/rent'
    | '/vault'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/games'
    | '/admin/history'
    | '/admin/homepage'
    | '/admin/logs'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/purpose-pages'
    | '/admin/rentals'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auctions/$slug'
    | '/blog/$slug'
    | '/brands/$brand'
    | '/cars/$slug'
    | '/games/engine-sound'
    | '/games/guess-the-car'
    | '/purpose/$slug'
    | '/rent/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auctions'
    | '/blog'
    | '/buy'
    | '/fleet'
    | '/games'
    | '/history'
    | '/rent'
    | '/vault'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/games'
    | '/admin/history'
    | '/admin/homepage'
    | '/admin/logs'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/purpose-pages'
    | '/admin/rentals'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auctions/$slug'
    | '/blog/$slug'
    | '/brands/$brand'
    | '/cars/$slug'
    | '/games/engine-sound'
    | '/games/guess-the-car'
    | '/purpose/$slug'
    | '/rent/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuctionsRoute: typeof AuctionsRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BuyRoute: typeof BuyRoute
  FleetRoute: typeof FleetRoute
  GamesRoute: typeof GamesRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  RentRoute: typeof RentRouteWithChildren
  VaultRoute: typeof VaultRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPurposePagesRoute: typeof AdminPurposePagesRoute
  AdminRentalsRoute: typeof AdminRentalsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  BrandsBrandRoute: typeof BrandsBrandRoute
  CarsSlugRoute: typeof CarsSlugRoute
  PurposeSlugRoute: typeof PurposeSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$slug': {
      id: '/rent/$slug'
      path: '/$slug'
      fullPath: '/rent/$slug'
      preLoaderRoute: typeof RentSlugRouteImport
      parentRoute: typeof RentRoute
    }
    '/purpose/$slug': {
      id: '/purpose/$slug'
      path: '/purpose/$slug'
      fullPath: '/purpose/$slug'
      preLoaderRoute: typeof PurposeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/guess-the-car': {
      id: '/games/guess-the-car'
      path: '/guess-the-car'
      fullPath: '/games/guess-the-car'
      preLoaderRoute: typeof GamesGuessTheCarRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/engine-sound': {
      id: '/games/engine-sound'
      path: '/engine-sound'
      fullPath: '/games/engine-sound'
      preLoaderRoute: typeof GamesEngineSoundRouteImport
      parentRoute: typeof GamesRoute
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brand': {
      id: '/brands/$brand'
      path: '/brands/$brand'
      fullPath: '/brands/$brand'
      preLoaderRoute: typeof BrandsBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auctions/$slug': {
      id: '/auctions/$slug'
      path: '/$slug'
      fullPath: '/auctions/$slug'
      preLoaderRoute: typeof AuctionsSlugRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/admin/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/purpose-pages': {
      id: '/admin/purpose-pages'
      path: '/admin/purpose-pages'
      fullPath: '/admin/purpose-pages'
      preLoaderRoute: typeof AdminPurposePagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/admin/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/admin/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuctionsRouteChildren {
  AuctionsSlugRoute: typeof AuctionsSlugRoute
}

const AuctionsRouteChildren: AuctionsRouteChildren = {
  AuctionsSlugRoute: AuctionsSlugRoute,
}

const AuctionsRouteWithChildren = AuctionsRoute._addFileChildren(
  AuctionsRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GamesRouteChildren {
  GamesEngineSoundRoute: typeof GamesEngineSoundRoute
  GamesGuessTheCarRoute: typeof GamesGuessTheCarRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesEngineSoundRoute: GamesEngineSoundRoute,
  GamesGuessTheCarRoute: GamesGuessTheCarRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface RentRouteChildren {
  RentSlugRoute: typeof RentSlugRoute
}

const RentRouteChildren: RentRouteChildren = {
  RentSlugRoute: RentSlugRoute,
}

const RentRouteWithChildren = RentRoute._addFileChildren(RentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuctionsRoute: AuctionsRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BuyRoute: BuyRoute,
  FleetRoute: FleetRoute,
  GamesRoute: GamesRouteWithChildren,
  HistoryRoute: HistoryRoute,
  RentRoute: RentRouteWithChildren,
  VaultRoute: VaultRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPurposePagesRoute: AdminPurposePagesRoute,
  AdminRentalsRoute: AdminRentalsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  BrandsBrandRoute: BrandsBrandRoute,
  CarsSlugRoute: CarsSlugRoute,
  PurposeSlugRoute: PurposeSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
